/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The organization's credit balance with its auto-pay configuration and live burn rate. Mirrors the dashboard's balance contract field for field. No payment-instrument detail appears here — saved cards live behind separate admin-only routes.
 * 
 * @export
 * @interface Balance
 */
export interface Balance {
    /**
     * Remaining credit in USD cents. May be negative when usage has outrun the balance.
     * @type {number}
     * @memberof Balance
     */
    balanceCents: number;
    /**
     * The same figure in dollars, for display.
     * @type {number}
     * @memberof Balance
     */
    balanceDollars: number;
    /**
     * 
     * @type {boolean}
     * @memberof Balance
     */
    autoPayEnabled: boolean;
    /**
     * Auto-pay triggers when the balance falls below this. Meaningful only when auto_pay_enabled.
     * @type {number}
     * @memberof Balance
     */
    autoPayThresholdCents: number;
    /**
     * Amount auto-pay charges when it triggers. Meaningful only when auto_pay_enabled.
     * @type {number}
     * @memberof Balance
     */
    autoPayAmountCents: number;
    /**
     * Live burn rate in USD cents per hour: the committed hourly price of every instance that is live, counted from launch — so instances still creating, provisioning or booting are included, not only those that have reached running. 0 when nothing is live.
     * 
     * `null` means the burn rate could not be determined. Treat that as unknown, never as 0: reading an unavailable burn rate as "nothing running" reports unbounded runway to an organization that may be minutes from empty.
     * @type {number}
     * @memberof Balance
     */
    burnCentsPerHour: number | null;
}

/**
 * Check if a given object implements the Balance interface.
 */
export function instanceOfBalance(value: object): value is Balance {
    if ((!('balanceCents' in (value as Record<string, any>)) && !('balance_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['balanceCents'] === undefined && (value as Record<string, any>)['balance_cents'] === undefined)) return false;
    if ((!('balanceDollars' in (value as Record<string, any>)) && !('balance_dollars' in (value as Record<string, any>))) || ((value as Record<string, any>)['balanceDollars'] === undefined && (value as Record<string, any>)['balance_dollars'] === undefined)) return false;
    if ((!('autoPayEnabled' in (value as Record<string, any>)) && !('auto_pay_enabled' in (value as Record<string, any>))) || ((value as Record<string, any>)['autoPayEnabled'] === undefined && (value as Record<string, any>)['auto_pay_enabled'] === undefined)) return false;
    if ((!('autoPayThresholdCents' in (value as Record<string, any>)) && !('auto_pay_threshold_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['autoPayThresholdCents'] === undefined && (value as Record<string, any>)['auto_pay_threshold_cents'] === undefined)) return false;
    if ((!('autoPayAmountCents' in (value as Record<string, any>)) && !('auto_pay_amount_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['autoPayAmountCents'] === undefined && (value as Record<string, any>)['auto_pay_amount_cents'] === undefined)) return false;
    if ((!('burnCentsPerHour' in (value as Record<string, any>)) && !('burn_cents_per_hour' in (value as Record<string, any>))) || ((value as Record<string, any>)['burnCentsPerHour'] === undefined && (value as Record<string, any>)['burn_cents_per_hour'] === undefined)) return false;
    return true;
}

export function BalanceFromJSON(json: any): Balance {
    return BalanceFromJSONTyped(json, false);
}

export function BalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Balance {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceCents': json['balance_cents'],
        'balanceDollars': json['balance_dollars'],
        'autoPayEnabled': json['auto_pay_enabled'],
        'autoPayThresholdCents': json['auto_pay_threshold_cents'],
        'autoPayAmountCents': json['auto_pay_amount_cents'],
        'burnCentsPerHour': json['burn_cents_per_hour'],
    };
}

export function BalanceToJSON(json: any): Balance {
    return BalanceToJSONTyped(json, false);
}

export function BalanceToJSONTyped(value?: Balance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance_cents': value['balanceCents'],
        'balance_dollars': value['balanceDollars'],
        'auto_pay_enabled': value['autoPayEnabled'],
        'auto_pay_threshold_cents': value['autoPayThresholdCents'],
        'auto_pay_amount_cents': value['autoPayAmountCents'],
        'burn_cents_per_hour': value['burnCentsPerHour'],
    };
}

