/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The verdict for one (organization, model) pair: what would happen if the model were invoked right now.
 * 
 * @export
 * @interface InferencePreflight
 */
export interface InferencePreflight {
    /**
     * The canonical catalog id the request resolved to.
     * @type {string}
     * @memberof InferencePreflight
     */
    model: string;
    /**
     * `ok` — the request will be served (covered by the plan, or payable). `warn` — it will be served AND charged in a way the caller may not expect. `block` — it will be refused (402 or 429).
     * @type {InferencePreflightVerdictEnum}
     * @memberof InferencePreflight
     */
    verdict: InferencePreflightVerdictEnum;
    /**
     * Stable code explaining the verdict, for clients that need their own wording. Absent on a plain `ok` that needs no explanation.
     * @type {InferencePreflightReasonEnum}
     * @memberof InferencePreflight
     */
    reason?: InferencePreflightReasonEnum;
    /**
     * A ready-to-print sentence, phrased for this exact plan/credit combination. Prefer it over composing one from verdict and reason: it improves without a client release.
     * @type {string}
     * @memberof InferencePreflight
     */
    message: string;
    /**
     * Whether the subscription tier covers this model. A property of the PLATFORM, not of the caller — it stays true for an organization that has no subscription, which is what makes the "this is included in the plan" upsell honest.
     * @type {boolean}
     * @memberof InferencePreflight
     */
    planCovered: boolean;
    /**
     * Whether the organization is entitled to the plan right now.
     * @type {boolean}
     * @memberof InferencePreflight
     */
    subscribed: boolean;
    /**
     * Whether a pay-as-you-go request could be paid for right now: a positive credit balance AND no self-set spending cap already at its limit. A boolean and never a figure — this route is on the inference read scope and must not disclose the balance.
     * @type {boolean}
     * @memberof InferencePreflight
     */
    funded: boolean;
}


/**
 * @export
 */
export const InferencePreflightVerdictEnum = {
    Ok: 'ok',
    Warn: 'warn',
    Block: 'block'
} as const;
export type InferencePreflightVerdictEnum = typeof InferencePreflightVerdictEnum[keyof typeof InferencePreflightVerdictEnum];

/**
 * @export
 */
export const InferencePreflightReasonEnum = {
    PlanCovered: 'plan_covered',
    Payg: 'payg',
    NotPlanCovered: 'not_plan_covered',
    SubscriptionQuotaExhausted: 'subscription_quota_exhausted',
    InsufficientBalance: 'insufficient_balance',
    DailyLimitReached: 'daily_limit_reached',
    MonthlyLimitReached: 'monthly_limit_reached',
    PreflightUnavailable: 'preflight_unavailable'
} as const;
export type InferencePreflightReasonEnum = typeof InferencePreflightReasonEnum[keyof typeof InferencePreflightReasonEnum];


/**
 * Check if a given object implements the InferencePreflight interface.
 */
export function instanceOfInferencePreflight(value: object): value is InferencePreflight {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if ((!('planCovered' in (value as Record<string, any>)) && !('plan_covered' in (value as Record<string, any>))) || ((value as Record<string, any>)['planCovered'] === undefined && (value as Record<string, any>)['plan_covered'] === undefined)) return false;
    if (!('subscribed' in value) || value['subscribed'] === undefined) return false;
    if (!('funded' in value) || value['funded'] === undefined) return false;
    return true;
}

export function InferencePreflightFromJSON(json: any): InferencePreflight {
    return InferencePreflightFromJSONTyped(json, false);
}

export function InferencePreflightFromJSONTyped(json: any, ignoreDiscriminator: boolean): InferencePreflight {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'verdict': json['verdict'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'message': json['message'],
        'planCovered': json['plan_covered'],
        'subscribed': json['subscribed'],
        'funded': json['funded'],
    };
}

export function InferencePreflightToJSON(json: any): InferencePreflight {
    return InferencePreflightToJSONTyped(json, false);
}

export function InferencePreflightToJSONTyped(value?: InferencePreflight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'verdict': value['verdict'],
        'reason': value['reason'],
        'message': value['message'],
        'plan_covered': value['planCovered'],
        'subscribed': value['subscribed'],
        'funded': value['funded'],
    };
}

