/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelRate } from './ModelRate';
import {
    ModelRateFromJSON,
    ModelRateFromJSONTyped,
    ModelRateToJSON,
    ModelRateToJSONTyped,
} from './ModelRate';
import type { PeakWindow } from './PeakWindow';
import {
    PeakWindowFromJSON,
    PeakWindowFromJSONTyped,
    PeakWindowToJSON,
    PeakWindowToJSONTyped,
} from './PeakWindow';

/**
 * 
 * @export
 * @interface ModelPricing
 */
export interface ModelPricing {
    /**
     * 
     * @type {string}
     * @memberof ModelPricing
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    inputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    outputPer1mTokensCents?: number;
    /**
     * Exact per-1M-token rate in micro-cents (1e-6 cent) for the cache-HIT part of a chat prompt (usage.prompt_tokens_details.cached_tokens). Present only on models with a published cached-input rate; absent means no discount — every prompt token bills at input_per_1m_tokens_cents. Treat this field as the presence signal: cached rates are routinely sub-cent, so the rounded cents field below is often omitted.
     * @type {number}
     * @memberof ModelPricing
     */
    cachedInputPer1mTokensMicrocents?: number;
    /**
     * cached_input_per_1m_tokens_microcents rounded to whole cents; omitted when the exact rate rounds below half a cent.
     * @type {number}
     * @memberof ModelPricing
     */
    cachedInputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    perImageCents?: number;
    /**
     * Exact per-image rate in micro-cents (1e-6 cent). Prefer this for image models — per_image_cents rounds sub-cent prices to 0.
     * @type {number}
     * @memberof ModelPricing
     */
    perImageMicrocents?: number;
    /**
     * Price per output megapixel in micro-cents (1e-6 cent) for image models metered per megapixel. Mutually exclusive with the per-image fields.
     * @type {number}
     * @memberof ModelPricing
     */
    perMpxlMicrocents?: number;
    /**
     * Representative per-clip price in micro-cents (1e-6 cent) for video models — a "from" price taken from the provider's published example rate.
     * @type {number}
     * @memberof ModelPricing
     */
    perVideoMicrocents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPricing
     */
    perVideoSecondCents?: number;
    /**
     * Exact per-second-of-output-video rate in micro-cents (1e-6 cent). Prefer this for video models.
     * @type {number}
     * @memberof ModelPricing
     */
    perVideoSecondMicrocents?: number;
    /**
     * Present only on a model priced by time of day. Which side of the peak schedule the instant this response was rendered falls on; the flat rate fields above are the rates in effect at that instant. A request is billed at the rate in effect when it ARRIVES (UTC), so a caller planning a call for later should price it from `peak` / `off_peak` and `peak_windows_utc`.
     * @type {ModelPricingPeriodEnum}
     * @memberof ModelPricing
     */
    period?: ModelPricingPeriodEnum;
    /**
     * The daily UTC ranges during which the `peak` rates apply, start inclusive and end exclusive ("24:00" is a valid end; a range whose end sorts before its start wraps midnight). Present only on a model priced by time of day.
     * @type {Array<PeakWindow>}
     * @memberof ModelPricing
     */
    peakWindowsUtc?: Array<PeakWindow>;
    /**
     * 
     * @type {ModelRate}
     * @memberof ModelPricing
     */
    peak?: ModelRate;
    /**
     * 
     * @type {ModelRate}
     * @memberof ModelPricing
     */
    offPeak?: ModelRate;
}


/**
 * @export
 */
export const ModelPricingPeriodEnum = {
    Peak: 'peak',
    OffPeak: 'off_peak'
} as const;
export type ModelPricingPeriodEnum = typeof ModelPricingPeriodEnum[keyof typeof ModelPricingPeriodEnum];


/**
 * Check if a given object implements the ModelPricing interface.
 */
export function instanceOfModelPricing(value: object): value is ModelPricing {
    return true;
}

export function ModelPricingFromJSON(json: any): ModelPricing {
    return ModelPricingFromJSONTyped(json, false);
}

export function ModelPricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPricing {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'inputPer1mTokensCents': json['input_per_1m_tokens_cents'] == null ? undefined : json['input_per_1m_tokens_cents'],
        'outputPer1mTokensCents': json['output_per_1m_tokens_cents'] == null ? undefined : json['output_per_1m_tokens_cents'],
        'cachedInputPer1mTokensMicrocents': json['cached_input_per_1m_tokens_microcents'] == null ? undefined : json['cached_input_per_1m_tokens_microcents'],
        'cachedInputPer1mTokensCents': json['cached_input_per_1m_tokens_cents'] == null ? undefined : json['cached_input_per_1m_tokens_cents'],
        'perImageCents': json['per_image_cents'] == null ? undefined : json['per_image_cents'],
        'perImageMicrocents': json['per_image_microcents'] == null ? undefined : json['per_image_microcents'],
        'perMpxlMicrocents': json['per_mpxl_microcents'] == null ? undefined : json['per_mpxl_microcents'],
        'perVideoMicrocents': json['per_video_microcents'] == null ? undefined : json['per_video_microcents'],
        'perVideoSecondCents': json['per_video_second_cents'] == null ? undefined : json['per_video_second_cents'],
        'perVideoSecondMicrocents': json['per_video_second_microcents'] == null ? undefined : json['per_video_second_microcents'],
        'period': json['period'] == null ? undefined : json['period'],
        'peakWindowsUtc': json['peak_windows_utc'] == null ? undefined : ((json['peak_windows_utc'] as Array<any>).map(PeakWindowFromJSON)),
        'peak': json['peak'] == null ? undefined : ModelRateFromJSON(json['peak']),
        'offPeak': json['off_peak'] == null ? undefined : ModelRateFromJSON(json['off_peak']),
    };
}

export function ModelPricingToJSON(json: any): ModelPricing {
    return ModelPricingToJSONTyped(json, false);
}

export function ModelPricingToJSONTyped(value?: ModelPricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'input_per_1m_tokens_cents': value['inputPer1mTokensCents'],
        'output_per_1m_tokens_cents': value['outputPer1mTokensCents'],
        'cached_input_per_1m_tokens_microcents': value['cachedInputPer1mTokensMicrocents'],
        'cached_input_per_1m_tokens_cents': value['cachedInputPer1mTokensCents'],
        'per_image_cents': value['perImageCents'],
        'per_image_microcents': value['perImageMicrocents'],
        'per_mpxl_microcents': value['perMpxlMicrocents'],
        'per_video_microcents': value['perVideoMicrocents'],
        'per_video_second_cents': value['perVideoSecondCents'],
        'per_video_second_microcents': value['perVideoSecondMicrocents'],
        'period': value['period'],
        'peak_windows_utc': value['peakWindowsUtc'] == null ? undefined : ((value['peakWindowsUtc'] as Array<any>).map(PeakWindowToJSON)),
        'peak': ModelRateToJSON(value['peak']),
        'off_peak': ModelRateToJSON(value['offPeak']),
    };
}

