/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One per-1M-token rate triple, in rounded cents and exact micro-cents (1e-6 cent). Prefer the micro-cent fields for arithmetic; cached rates are routinely sub-cent and their cents field is then omitted.
 * @export
 * @interface ModelRate
 */
export interface ModelRate {
    /**
     * 
     * @type {number}
     * @memberof ModelRate
     */
    inputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelRate
     */
    inputPer1mTokensMicrocents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelRate
     */
    cachedInputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelRate
     */
    cachedInputPer1mTokensMicrocents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelRate
     */
    outputPer1mTokensCents?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelRate
     */
    outputPer1mTokensMicrocents?: number;
}

/**
 * Check if a given object implements the ModelRate interface.
 */
export function instanceOfModelRate(value: object): value is ModelRate {
    return true;
}

export function ModelRateFromJSON(json: any): ModelRate {
    return ModelRateFromJSONTyped(json, false);
}

export function ModelRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelRate {
    if (json == null) {
        return json;
    }
    return {
        
        'inputPer1mTokensCents': json['input_per_1m_tokens_cents'] == null ? undefined : json['input_per_1m_tokens_cents'],
        'inputPer1mTokensMicrocents': json['input_per_1m_tokens_microcents'] == null ? undefined : json['input_per_1m_tokens_microcents'],
        'cachedInputPer1mTokensCents': json['cached_input_per_1m_tokens_cents'] == null ? undefined : json['cached_input_per_1m_tokens_cents'],
        'cachedInputPer1mTokensMicrocents': json['cached_input_per_1m_tokens_microcents'] == null ? undefined : json['cached_input_per_1m_tokens_microcents'],
        'outputPer1mTokensCents': json['output_per_1m_tokens_cents'] == null ? undefined : json['output_per_1m_tokens_cents'],
        'outputPer1mTokensMicrocents': json['output_per_1m_tokens_microcents'] == null ? undefined : json['output_per_1m_tokens_microcents'],
    };
}

export function ModelRateToJSON(json: any): ModelRate {
    return ModelRateToJSONTyped(json, false);
}

export function ModelRateToJSONTyped(value?: ModelRate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_per_1m_tokens_cents': value['inputPer1mTokensCents'],
        'input_per_1m_tokens_microcents': value['inputPer1mTokensMicrocents'],
        'cached_input_per_1m_tokens_cents': value['cachedInputPer1mTokensCents'],
        'cached_input_per_1m_tokens_microcents': value['cachedInputPer1mTokensMicrocents'],
        'output_per_1m_tokens_cents': value['outputPer1mTokensCents'],
        'output_per_1m_tokens_microcents': value['outputPer1mTokensMicrocents'],
    };
}

