/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One daily UTC time range during which a model's peak rates apply.
 * @export
 * @interface PeakWindow
 */
export interface PeakWindow {
    /**
     * "HH:MM" UTC, inclusive.
     * @type {string}
     * @memberof PeakWindow
     */
    start: string;
    /**
     * "HH:MM" UTC, exclusive ("24:00" means until midnight).
     * @type {string}
     * @memberof PeakWindow
     */
    end: string;
}

/**
 * Check if a given object implements the PeakWindow interface.
 */
export function instanceOfPeakWindow(value: object): value is PeakWindow {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function PeakWindowFromJSON(json: any): PeakWindow {
    return PeakWindowFromJSONTyped(json, false);
}

export function PeakWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeakWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function PeakWindowToJSON(json: any): PeakWindow {
    return PeakWindowToJSONTyped(json, false);
}

export function PeakWindowToJSONTyped(value?: PeakWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

