/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RefereeStatus } from './RefereeStatus';
import {
    RefereeStatusFromJSON,
    RefereeStatusFromJSONTyped,
    RefereeStatusToJSON,
    RefereeStatusToJSONTyped,
} from './RefereeStatus';

/**
 * The organization's referral-program view: its invite link, the program terms, its referrer stats, and (only when it was itself referred) its referee progress. Amounts are USD cents.
 * 
 * @export
 * @interface Referral
 */
export interface Referral {
    /**
     * The organization's shareable referral code, e.g. `GPU-7KQ2-M4XP`.
     * @type {string}
     * @memberof Referral
     */
    code: string;
    /**
     * The ready-to-share invite link, `{site}/r/{code}`.
     * @type {string}
     * @memberof Referral
     */
    inviteUrl: string;
    /**
     * Friends who signed up through the link but have not yet reached the spend gate.
     * @type {number}
     * @memberof Referral
     */
    pending: number;
    /**
     * Friends past the spend gate whose reward is inside the chargeback hold.
     * @type {number}
     * @memberof Referral
     */
    qualified: number;
    /**
     * Referrals that have paid out.
     * @type {number}
     * @memberof Referral
     */
    settled: number;
    /**
     * Total credit paid to this organization as a referrer.
     * @type {number}
     * @memberof Referral
     */
    earnedCents: number;
    /**
     * Credit paid to the referrer per settled referral.
     * @type {number}
     * @memberof Referral
     */
    rewardCents: number;
    /**
     * Credit paid to the referred friend per settled referral.
     * @type {number}
     * @memberof Referral
     */
    refereeRewardCents: number;
    /**
     * The friend's cumulative inference spend that qualifies a referral.
     * @type {number}
     * @memberof Referral
     */
    qualifySpendCents: number;
    /**
     * Days between qualification and payout (chargeback hold).
     * @type {number}
     * @memberof Referral
     */
    holdDays: number;
    /**
     * 
     * @type {RefereeStatus}
     * @memberof Referral
     */
    referred?: RefereeStatus;
}

/**
 * Check if a given object implements the Referral interface.
 */
export function instanceOfReferral(value: object): value is Referral {
    if (!('code' in value) || value['code'] === undefined) return false;
    if ((!('inviteUrl' in (value as Record<string, any>)) && !('invite_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['inviteUrl'] === undefined && (value as Record<string, any>)['invite_url'] === undefined)) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('qualified' in value) || value['qualified'] === undefined) return false;
    if (!('settled' in value) || value['settled'] === undefined) return false;
    if ((!('earnedCents' in (value as Record<string, any>)) && !('earned_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['earnedCents'] === undefined && (value as Record<string, any>)['earned_cents'] === undefined)) return false;
    if ((!('rewardCents' in (value as Record<string, any>)) && !('reward_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['rewardCents'] === undefined && (value as Record<string, any>)['reward_cents'] === undefined)) return false;
    if ((!('refereeRewardCents' in (value as Record<string, any>)) && !('referee_reward_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['refereeRewardCents'] === undefined && (value as Record<string, any>)['referee_reward_cents'] === undefined)) return false;
    if ((!('qualifySpendCents' in (value as Record<string, any>)) && !('qualify_spend_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['qualifySpendCents'] === undefined && (value as Record<string, any>)['qualify_spend_cents'] === undefined)) return false;
    if ((!('holdDays' in (value as Record<string, any>)) && !('hold_days' in (value as Record<string, any>))) || ((value as Record<string, any>)['holdDays'] === undefined && (value as Record<string, any>)['hold_days'] === undefined)) return false;
    return true;
}

export function ReferralFromJSON(json: any): Referral {
    return ReferralFromJSONTyped(json, false);
}

export function ReferralFromJSONTyped(json: any, ignoreDiscriminator: boolean): Referral {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'inviteUrl': json['invite_url'],
        'pending': json['pending'],
        'qualified': json['qualified'],
        'settled': json['settled'],
        'earnedCents': json['earned_cents'],
        'rewardCents': json['reward_cents'],
        'refereeRewardCents': json['referee_reward_cents'],
        'qualifySpendCents': json['qualify_spend_cents'],
        'holdDays': json['hold_days'],
        'referred': json['referred'] == null ? undefined : RefereeStatusFromJSON(json['referred']),
    };
}

export function ReferralToJSON(json: any): Referral {
    return ReferralToJSONTyped(json, false);
}

export function ReferralToJSONTyped(value?: Referral | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'invite_url': value['inviteUrl'],
        'pending': value['pending'],
        'qualified': value['qualified'],
        'settled': value['settled'],
        'earned_cents': value['earnedCents'],
        'reward_cents': value['rewardCents'],
        'referee_reward_cents': value['refereeRewardCents'],
        'qualify_spend_cents': value['qualifySpendCents'],
        'hold_days': value['holdDays'],
        'referred': RefereeStatusToJSON(value['referred']),
    };
}

