/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present only when the organization signed up through someone else's invite link: where that referral sits and how far the organization is from unlocking its own reward.
 * 
 * @export
 * @interface RefereeStatus
 */
export interface RefereeStatus {
    /**
     * Lifecycle state. `pending` until the spend gate is met; `qualified` inside the hold; `settled` once paid.
     * @type {RefereeStatusStatusEnum}
     * @memberof RefereeStatus
     */
    status: RefereeStatusStatusEnum;
    /**
     * Cumulative inference spend so far.
     * @type {number}
     * @memberof RefereeStatus
     */
    spentCents: number;
    /**
     * The spend that qualifies the referral.
     * @type {number}
     * @memberof RefereeStatus
     */
    qualifySpendCents: number;
    /**
     * What this organization receives on settlement.
     * @type {number}
     * @memberof RefereeStatus
     */
    rewardCents: number;
    /**
     * When the spend gate was met. Absent while pending.
     * @type {Date}
     * @memberof RefereeStatus
     */
    qualifiedAt?: Date;
    /**
     * When the hold ends and both halves pay out. Absent while pending.
     * @type {Date}
     * @memberof RefereeStatus
     */
    holdUntil?: Date;
    /**
     * When the reward was paid. Absent until settled.
     * @type {Date}
     * @memberof RefereeStatus
     */
    settledAt?: Date;
}


/**
 * @export
 */
export const RefereeStatusStatusEnum = {
    Pending: 'pending',
    Qualified: 'qualified',
    Settled: 'settled',
    Rejected: 'rejected'
} as const;
export type RefereeStatusStatusEnum = typeof RefereeStatusStatusEnum[keyof typeof RefereeStatusStatusEnum];


/**
 * Check if a given object implements the RefereeStatus interface.
 */
export function instanceOfRefereeStatus(value: object): value is RefereeStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('spentCents' in (value as Record<string, any>)) && !('spent_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['spentCents'] === undefined && (value as Record<string, any>)['spent_cents'] === undefined)) return false;
    if ((!('qualifySpendCents' in (value as Record<string, any>)) && !('qualify_spend_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['qualifySpendCents'] === undefined && (value as Record<string, any>)['qualify_spend_cents'] === undefined)) return false;
    if ((!('rewardCents' in (value as Record<string, any>)) && !('reward_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['rewardCents'] === undefined && (value as Record<string, any>)['reward_cents'] === undefined)) return false;
    return true;
}

export function RefereeStatusFromJSON(json: any): RefereeStatus {
    return RefereeStatusFromJSONTyped(json, false);
}

export function RefereeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefereeStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'spentCents': json['spent_cents'],
        'qualifySpendCents': json['qualify_spend_cents'],
        'rewardCents': json['reward_cents'],
        'qualifiedAt': json['qualified_at'] == null ? undefined : (new Date(json['qualified_at'])),
        'holdUntil': json['hold_until'] == null ? undefined : (new Date(json['hold_until'])),
        'settledAt': json['settled_at'] == null ? undefined : (new Date(json['settled_at'])),
    };
}

export function RefereeStatusToJSON(json: any): RefereeStatus {
    return RefereeStatusToJSONTyped(json, false);
}

export function RefereeStatusToJSONTyped(value?: RefereeStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'spent_cents': value['spentCents'],
        'qualify_spend_cents': value['qualifySpendCents'],
        'reward_cents': value['rewardCents'],
        'qualified_at': value['qualifiedAt'] == null ? value['qualifiedAt'] : value['qualifiedAt'].toISOString(),
        'hold_until': value['holdUntil'] == null ? value['holdUntil'] : value['holdUntil'].toISOString(),
        'settled_at': value['settledAt'] == null ? value['settledAt'] : value['settledAt'].toISOString(),
    };
}

