/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The plan's recurring charge, read live from the billing provider — the single source of truth, never a number embedded in code.
 * 
 * ABSENT means "price unavailable right now" (billing unconfigured, or the provider could not be reached). It NEVER means free. Render the plan without a figure rather than substituting one; the hosted checkout page always shows the real amount.
 * 
 * @export
 * @interface SubscriptionPrice
 */
export interface SubscriptionPrice {
    /**
     * Amount in the currency's minor unit (299 = $2.99).
     * @type {number}
     * @memberof SubscriptionPrice
     */
    amountCents: number;
    /**
     * ISO 4217 currency code, lower-case (e.g. "usd").
     * @type {string}
     * @memberof SubscriptionPrice
     */
    currency: string;
    /**
     * Recurrence unit — "day", "week", "month" or "year".
     * @type {string}
     * @memberof SubscriptionPrice
     */
    interval: string;
    /**
     * How many intervals between charges ("month", 1 = monthly).
     * @type {number}
     * @memberof SubscriptionPrice
     */
    intervalCount: number;
}

/**
 * Check if a given object implements the SubscriptionPrice interface.
 */
export function instanceOfSubscriptionPrice(value: object): value is SubscriptionPrice {
    if ((!('amountCents' in (value as Record<string, any>)) && !('amount_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['amountCents'] === undefined && (value as Record<string, any>)['amount_cents'] === undefined)) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if ((!('intervalCount' in (value as Record<string, any>)) && !('interval_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['intervalCount'] === undefined && (value as Record<string, any>)['interval_count'] === undefined)) return false;
    return true;
}

export function SubscriptionPriceFromJSON(json: any): SubscriptionPrice {
    return SubscriptionPriceFromJSONTyped(json, false);
}

export function SubscriptionPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'currency': json['currency'],
        'interval': json['interval'],
        'intervalCount': json['interval_count'],
    };
}

export function SubscriptionPriceToJSON(json: any): SubscriptionPrice {
    return SubscriptionPriceToJSONTyped(json, false);
}

export function SubscriptionPriceToJSONTyped(value?: SubscriptionPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'currency': value['currency'],
        'interval': value['interval'],
        'interval_count': value['intervalCount'],
    };
}

