/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPlan } from './SubscriptionPlan';
import {
    SubscriptionPlanFromJSON,
    SubscriptionPlanFromJSONTyped,
    SubscriptionPlanToJSON,
    SubscriptionPlanToJSONTyped,
} from './SubscriptionPlan';
import type { SubscriptionUsage } from './SubscriptionUsage';
import {
    SubscriptionUsageFromJSON,
    SubscriptionUsageFromJSONTyped,
    SubscriptionUsageToJSON,
    SubscriptionUsageToJSONTyped,
} from './SubscriptionUsage';
import type { SubscriptionQuota } from './SubscriptionQuota';
import {
    SubscriptionQuotaFromJSON,
    SubscriptionQuotaFromJSONTyped,
    SubscriptionQuotaToJSON,
    SubscriptionQuotaToJSONTyped,
} from './SubscriptionQuota';

/**
 * The organization's flat subscription tier: entitlement, billing period, the configured quota, and consumption against it. The console and this endpoint assemble it from the same source, so the two surfaces cannot report different numbers.
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * Whether the organization is entitled to the plan right now. Only an `active` or `trialing` subscription entitles, including a short grace window past the period end that absorbs renewal webhook lag; a failed payment (`past_due`) cuts access immediately. Render from this; do not re-derive entitlement from `status` and the period bounds.
     * @type {boolean}
     * @memberof Subscription
     */
    subscribed: boolean;
    /**
     * Raw subscription status — "active", "trialing", "past_due", "canceled" and so on — or "none" when the organization never subscribed.
     * @type {string}
     * @memberof Subscription
     */
    status: string;
    /**
     * Whether the subscription stops at the end of the current period instead of renewing.
     * @type {boolean}
     * @memberof Subscription
     */
    cancelAtPeriodEnd: boolean;
    /**
     * Start of the current billing period. Absent until the billing provider has reported a period for this subscription.
     * @type {Date}
     * @memberof Subscription
     */
    currentPeriodStart?: Date;
    /**
     * End of the current billing period. Absent under the same condition as current_period_start.
     * @type {Date}
     * @memberof Subscription
     */
    currentPeriodEnd?: Date;
    /**
     * 
     * @type {SubscriptionPlan}
     * @memberof Subscription
     */
    plan: SubscriptionPlan;
    /**
     * 
     * @type {SubscriptionQuota}
     * @memberof Subscription
     */
    quota: SubscriptionQuota;
    /**
     * 
     * @type {SubscriptionUsage}
     * @memberof Subscription
     */
    usage?: SubscriptionUsage;
}

/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('subscribed' in value) || value['subscribed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('cancelAtPeriodEnd' in (value as Record<string, any>)) && !('cancel_at_period_end' in (value as Record<string, any>))) || ((value as Record<string, any>)['cancelAtPeriodEnd'] === undefined && (value as Record<string, any>)['cancel_at_period_end'] === undefined)) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    if (!('quota' in value) || value['quota'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'subscribed': json['subscribed'],
        'status': json['status'],
        'cancelAtPeriodEnd': json['cancel_at_period_end'],
        'currentPeriodStart': json['current_period_start'] == null ? undefined : (new Date(json['current_period_start'])),
        'currentPeriodEnd': json['current_period_end'] == null ? undefined : (new Date(json['current_period_end'])),
        'plan': SubscriptionPlanFromJSON(json['plan']),
        'quota': SubscriptionQuotaFromJSON(json['quota']),
        'usage': json['usage'] == null ? undefined : SubscriptionUsageFromJSON(json['usage']),
    };
}

export function SubscriptionToJSON(json: any): Subscription {
    return SubscriptionToJSONTyped(json, false);
}

export function SubscriptionToJSONTyped(value?: Subscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscribed': value['subscribed'],
        'status': value['status'],
        'cancel_at_period_end': value['cancelAtPeriodEnd'],
        'current_period_start': value['currentPeriodStart'] == null ? value['currentPeriodStart'] : value['currentPeriodStart'].toISOString(),
        'current_period_end': value['currentPeriodEnd'] == null ? value['currentPeriodEnd'] : value['currentPeriodEnd'].toISOString(),
        'plan': SubscriptionPlanToJSON(value['plan']),
        'quota': SubscriptionQuotaToJSON(value['quota']),
        'usage': SubscriptionUsageToJSON(value['usage']),
    };
}

