/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionPortalSession
 */
export interface SubscriptionPortalSession {
    /**
     * The hosted billing portal — cancel, resume, change payment method, download invoices.
     * @type {string}
     * @memberof SubscriptionPortalSession
     */
    portalUrl: string;
}

/**
 * Check if a given object implements the SubscriptionPortalSession interface.
 */
export function instanceOfSubscriptionPortalSession(value: object): value is SubscriptionPortalSession {
    if ((!('portalUrl' in (value as Record<string, any>)) && !('portal_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['portalUrl'] === undefined && (value as Record<string, any>)['portal_url'] === undefined)) return false;
    return true;
}

export function SubscriptionPortalSessionFromJSON(json: any): SubscriptionPortalSession {
    return SubscriptionPortalSessionFromJSONTyped(json, false);
}

export function SubscriptionPortalSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPortalSession {
    if (json == null) {
        return json;
    }
    return {
        
        'portalUrl': json['portal_url'],
    };
}

export function SubscriptionPortalSessionToJSON(json: any): SubscriptionPortalSession {
    return SubscriptionPortalSessionToJSONTyped(json, false);
}

export function SubscriptionPortalSessionToJSONTyped(value?: SubscriptionPortalSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'portal_url': value['portalUrl'],
    };
}

