/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The plan's configured allowances — the denominators of the usage meter. Always present, including for an organization that has not subscribed, where it describes what subscribing would provide.
 * 
 * Token figures are WEIGHTED tokens: every model carries a usage factor, so a model at factor 2 spends two of these per token it serves.
 * 
 * @export
 * @interface SubscriptionQuota
 */
export interface SubscriptionQuota {
    /**
     * Weighted input tokens included per billing period.
     * @type {number}
     * @memberof SubscriptionQuota
     */
    inputTokensMonthly: number;
    /**
     * Weighted output tokens included per billing period. Reasoning tokens are output tokens.
     * @type {number}
     * @memberof SubscriptionQuota
     */
    outputTokensMonthly: number;
    /**
     * Weighted input+output tokens allowed over a ROLLING 7-day window. This cap slides with the clock; it does not reset with the billing period.
     * @type {number}
     * @memberof SubscriptionQuota
     */
    weeklyTokens: number;
    /**
     * Per-period backstop on list-price metered cost, in micro-cents (1e-6 cent). 0 means no backstop is configured on this deployment.
     * @type {number}
     * @memberof SubscriptionQuota
     */
    maxUsageMicroCents: number;
    /**
     * Deprecated and always 0. There is no subscriber discount on pay-as-you-go spend: a request that exhausts the plan quota bills at list rates, the same rates an org without a subscription pays. The field is retained so existing deserializers keep working and will be removed in the next breaking revision. Do not display it.
     * @type {number}
     * @memberof SubscriptionQuota
     * @deprecated
     */
    paygDiscountBp: number;
}

/**
 * Check if a given object implements the SubscriptionQuota interface.
 */
export function instanceOfSubscriptionQuota(value: object): value is SubscriptionQuota {
    if ((!('inputTokensMonthly' in (value as Record<string, any>)) && !('input_tokens_monthly' in (value as Record<string, any>))) || ((value as Record<string, any>)['inputTokensMonthly'] === undefined && (value as Record<string, any>)['input_tokens_monthly'] === undefined)) return false;
    if ((!('outputTokensMonthly' in (value as Record<string, any>)) && !('output_tokens_monthly' in (value as Record<string, any>))) || ((value as Record<string, any>)['outputTokensMonthly'] === undefined && (value as Record<string, any>)['output_tokens_monthly'] === undefined)) return false;
    if ((!('weeklyTokens' in (value as Record<string, any>)) && !('weekly_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['weeklyTokens'] === undefined && (value as Record<string, any>)['weekly_tokens'] === undefined)) return false;
    if ((!('maxUsageMicroCents' in (value as Record<string, any>)) && !('max_usage_micro_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxUsageMicroCents'] === undefined && (value as Record<string, any>)['max_usage_micro_cents'] === undefined)) return false;
    if ((!('paygDiscountBp' in (value as Record<string, any>)) && !('payg_discount_bp' in (value as Record<string, any>))) || ((value as Record<string, any>)['paygDiscountBp'] === undefined && (value as Record<string, any>)['payg_discount_bp'] === undefined)) return false;
    return true;
}

export function SubscriptionQuotaFromJSON(json: any): SubscriptionQuota {
    return SubscriptionQuotaFromJSONTyped(json, false);
}

export function SubscriptionQuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionQuota {
    if (json == null) {
        return json;
    }
    return {
        
        'inputTokensMonthly': json['input_tokens_monthly'],
        'outputTokensMonthly': json['output_tokens_monthly'],
        'weeklyTokens': json['weekly_tokens'],
        'maxUsageMicroCents': json['max_usage_micro_cents'],
        'paygDiscountBp': json['payg_discount_bp'],
    };
}

export function SubscriptionQuotaToJSON(json: any): SubscriptionQuota {
    return SubscriptionQuotaToJSONTyped(json, false);
}

export function SubscriptionQuotaToJSONTyped(value?: SubscriptionQuota | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_tokens_monthly': value['inputTokensMonthly'],
        'output_tokens_monthly': value['outputTokensMonthly'],
        'weekly_tokens': value['weeklyTokens'],
        'max_usage_micro_cents': value['maxUsageMicroCents'],
        'payg_discount_bp': value['paygDiscountBp'],
    };
}

