/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional overrides for a checkout mint. Every field has a deployment default, so an empty body is the normal call.
 * 
 * @export
 * @interface SubscriptionCheckoutRequest
 */
export interface SubscriptionCheckoutRequest {
    /**
     * Where the provider returns after a completed payment. Defaults to the deployment's configured URL.
     * @type {string}
     * @memberof SubscriptionCheckoutRequest
     */
    successUrl?: string;
    /**
     * Where the provider returns if checkout is abandoned. Defaults to the deployment's configured URL.
     * @type {string}
     * @memberof SubscriptionCheckoutRequest
     */
    cancelUrl?: string;
    /**
     * Pins the plan the client displayed. An unknown key is a 400 rather than a silent purchase of a different tier.
     * @type {string}
     * @memberof SubscriptionCheckoutRequest
     */
    planKey?: string;
}

/**
 * Check if a given object implements the SubscriptionCheckoutRequest interface.
 */
export function instanceOfSubscriptionCheckoutRequest(value: object): value is SubscriptionCheckoutRequest {
    return true;
}

export function SubscriptionCheckoutRequestFromJSON(json: any): SubscriptionCheckoutRequest {
    return SubscriptionCheckoutRequestFromJSONTyped(json, false);
}

export function SubscriptionCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCheckoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'successUrl': json['success_url'] == null ? undefined : json['success_url'],
        'cancelUrl': json['cancel_url'] == null ? undefined : json['cancel_url'],
        'planKey': json['plan_key'] == null ? undefined : json['plan_key'],
    };
}

export function SubscriptionCheckoutRequestToJSON(json: any): SubscriptionCheckoutRequest {
    return SubscriptionCheckoutRequestToJSONTyped(json, false);
}

export function SubscriptionCheckoutRequestToJSONTyped(value?: SubscriptionCheckoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success_url': value['successUrl'],
        'cancel_url': value['cancelUrl'],
        'plan_key': value['planKey'],
    };
}

