/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional overrides for a billing-portal mint.
 * @export
 * @interface SubscriptionPortalRequest
 */
export interface SubscriptionPortalRequest {
    /**
     * Where the provider returns when the customer leaves the portal. Defaults to the deployment's configured URL.
     * @type {string}
     * @memberof SubscriptionPortalRequest
     */
    returnUrl?: string;
}

/**
 * Check if a given object implements the SubscriptionPortalRequest interface.
 */
export function instanceOfSubscriptionPortalRequest(value: object): value is SubscriptionPortalRequest {
    return true;
}

export function SubscriptionPortalRequestFromJSON(json: any): SubscriptionPortalRequest {
    return SubscriptionPortalRequestFromJSONTyped(json, false);
}

export function SubscriptionPortalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPortalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'returnUrl': json['return_url'] == null ? undefined : json['return_url'],
    };
}

export function SubscriptionPortalRequestToJSON(json: any): SubscriptionPortalRequest {
    return SubscriptionPortalRequestToJSONTyped(json, false);
}

export function SubscriptionPortalRequestToJSONTyped(value?: SubscriptionPortalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'return_url': value['returnUrl'],
    };
}

