/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPrice } from './SubscriptionPrice';
import {
    SubscriptionPriceFromJSON,
    SubscriptionPriceFromJSONTyped,
    SubscriptionPriceToJSON,
    SubscriptionPriceToJSONTyped,
} from './SubscriptionPrice';

/**
 * What the organization is — or would be — subscribing to. Always present, including for an organization that never subscribed: it is what a point of purchase renders before sending anyone to pay.
 * 
 * @export
 * @interface SubscriptionPlan
 */
export interface SubscriptionPlan {
    /**
     * Stable identifier for the tier. Send it as `plan_key` on /billing/subscription/checkout to pin the plan you displayed.
     * @type {string}
     * @memberof SubscriptionPlan
     */
    key: string;
    /**
     * Human-facing plan name.
     * @type {string}
     * @memberof SubscriptionPlan
     */
    name: string;
    /**
     * 
     * @type {SubscriptionPrice}
     * @memberof SubscriptionPlan
     */
    price?: SubscriptionPrice;
}

/**
 * Check if a given object implements the SubscriptionPlan interface.
 */
export function instanceOfSubscriptionPlan(value: object): value is SubscriptionPlan {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SubscriptionPlanFromJSON(json: any): SubscriptionPlan {
    return SubscriptionPlanFromJSONTyped(json, false);
}

export function SubscriptionPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'name': json['name'],
        'price': json['price'] == null ? undefined : SubscriptionPriceFromJSON(json['price']),
    };
}

export function SubscriptionPlanToJSON(json: any): SubscriptionPlan {
    return SubscriptionPlanToJSONTyped(json, false);
}

export function SubscriptionPlanToJSONTyped(value?: SubscriptionPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'name': value['name'],
        'price': SubscriptionPriceToJSON(value['price']),
    };
}

