/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPlan } from './SubscriptionPlan';
import {
    SubscriptionPlanFromJSON,
    SubscriptionPlanFromJSONTyped,
    SubscriptionPlanToJSON,
    SubscriptionPlanToJSONTyped,
} from './SubscriptionPlan';

/**
 * 
 * @export
 * @interface SubscriptionCheckoutSession
 */
export interface SubscriptionCheckoutSession {
    /**
     * The hosted page the customer must open to pay.
     * @type {string}
     * @memberof SubscriptionCheckoutSession
     */
    checkoutUrl: string;
    /**
     * Checkout session id, for support correlation.
     * @type {string}
     * @memberof SubscriptionCheckoutSession
     */
    sessionId: string;
    /**
     * 
     * @type {SubscriptionPlan}
     * @memberof SubscriptionCheckoutSession
     */
    plan: SubscriptionPlan;
}

/**
 * Check if a given object implements the SubscriptionCheckoutSession interface.
 */
export function instanceOfSubscriptionCheckoutSession(value: object): value is SubscriptionCheckoutSession {
    if ((!('checkoutUrl' in (value as Record<string, any>)) && !('checkout_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['checkoutUrl'] === undefined && (value as Record<string, any>)['checkout_url'] === undefined)) return false;
    if ((!('sessionId' in (value as Record<string, any>)) && !('session_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['sessionId'] === undefined && (value as Record<string, any>)['session_id'] === undefined)) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    return true;
}

export function SubscriptionCheckoutSessionFromJSON(json: any): SubscriptionCheckoutSession {
    return SubscriptionCheckoutSessionFromJSONTyped(json, false);
}

export function SubscriptionCheckoutSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCheckoutSession {
    if (json == null) {
        return json;
    }
    return {
        
        'checkoutUrl': json['checkout_url'],
        'sessionId': json['session_id'],
        'plan': SubscriptionPlanFromJSON(json['plan']),
    };
}

export function SubscriptionCheckoutSessionToJSON(json: any): SubscriptionCheckoutSession {
    return SubscriptionCheckoutSessionToJSONTyped(json, false);
}

export function SubscriptionCheckoutSessionToJSONTyped(value?: SubscriptionCheckoutSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkout_url': value['checkoutUrl'],
        'session_id': value['sessionId'],
        'plan': SubscriptionPlanToJSON(value['plan']),
    };
}

