/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Consumption against the quota, from the same factor-weighted read the request-time gate evaluates — so this meter and enforcement cannot disagree.
 * 
 * Present only for an entitled subscription whose meter could be read. Its absence is never a statement that nothing was used.
 * 
 * @export
 * @interface SubscriptionUsage
 */
export interface SubscriptionUsage {
    /**
     * Start of the window the period figures were summed over: the subscription's current period, or the UTC calendar month when the billing provider has not reported one yet.
     * @type {Date}
     * @memberof SubscriptionUsage
     */
    periodStart: Date;
    /**
     * End of that window.
     * @type {Date}
     * @memberof SubscriptionUsage
     */
    periodEnd: Date;
    /**
     * Weighted input tokens spent this period, against `quota.input_tokens_monthly`.
     * @type {number}
     * @memberof SubscriptionUsage
     */
    weightedInputTokens: number;
    /**
     * Weighted output tokens spent this period, against `quota.output_tokens_monthly`.
     * @type {number}
     * @memberof SubscriptionUsage
     */
    weightedOutputTokens: number;
    /**
     * Weighted input+output tokens over the trailing 7 days, against `quota.weekly_tokens`. A rolling figure, not a period one — it can be non-zero moments after a period rolls over.
     * @type {number}
     * @memberof SubscriptionUsage
     */
    weeklyWeightedTokens: number;
    /**
     * List-price metered cost of this period's plan traffic in micro-cents (1e-6 cent), against `quota.max_usage_micro_cents`.
     * @type {number}
     * @memberof SubscriptionUsage
     */
    costMicroCents: number;
}

/**
 * Check if a given object implements the SubscriptionUsage interface.
 */
export function instanceOfSubscriptionUsage(value: object): value is SubscriptionUsage {
    if ((!('periodStart' in (value as Record<string, any>)) && !('period_start' in (value as Record<string, any>))) || ((value as Record<string, any>)['periodStart'] === undefined && (value as Record<string, any>)['period_start'] === undefined)) return false;
    if ((!('periodEnd' in (value as Record<string, any>)) && !('period_end' in (value as Record<string, any>))) || ((value as Record<string, any>)['periodEnd'] === undefined && (value as Record<string, any>)['period_end'] === undefined)) return false;
    if ((!('weightedInputTokens' in (value as Record<string, any>)) && !('weighted_input_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['weightedInputTokens'] === undefined && (value as Record<string, any>)['weighted_input_tokens'] === undefined)) return false;
    if ((!('weightedOutputTokens' in (value as Record<string, any>)) && !('weighted_output_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['weightedOutputTokens'] === undefined && (value as Record<string, any>)['weighted_output_tokens'] === undefined)) return false;
    if ((!('weeklyWeightedTokens' in (value as Record<string, any>)) && !('weekly_weighted_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['weeklyWeightedTokens'] === undefined && (value as Record<string, any>)['weekly_weighted_tokens'] === undefined)) return false;
    if ((!('costMicroCents' in (value as Record<string, any>)) && !('cost_micro_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['costMicroCents'] === undefined && (value as Record<string, any>)['cost_micro_cents'] === undefined)) return false;
    return true;
}

export function SubscriptionUsageFromJSON(json: any): SubscriptionUsage {
    return SubscriptionUsageFromJSONTyped(json, false);
}

export function SubscriptionUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'periodStart': (new Date(json['period_start'])),
        'periodEnd': (new Date(json['period_end'])),
        'weightedInputTokens': json['weighted_input_tokens'],
        'weightedOutputTokens': json['weighted_output_tokens'],
        'weeklyWeightedTokens': json['weekly_weighted_tokens'],
        'costMicroCents': json['cost_micro_cents'],
    };
}

export function SubscriptionUsageToJSON(json: any): SubscriptionUsage {
    return SubscriptionUsageToJSONTyped(json, false);
}

export function SubscriptionUsageToJSONTyped(value?: SubscriptionUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period_start': value['periodStart'].toISOString(),
        'period_end': value['periodEnd'].toISOString(),
        'weighted_input_tokens': value['weightedInputTokens'],
        'weighted_output_tokens': value['weightedOutputTokens'],
        'weekly_weighted_tokens': value['weeklyWeightedTokens'],
        'cost_micro_cents': value['costMicroCents'],
    };
}

