/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the Usage interface.
 */
export function instanceOfUsage(value: object): value is Usage {
    if ((!('promptTokens' in (value as Record<string, any>)) && !('prompt_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['promptTokens'] === undefined && (value as Record<string, any>)['prompt_tokens'] === undefined)) return false;
    if ((!('completionTokens' in (value as Record<string, any>)) && !('completion_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['completionTokens'] === undefined && (value as Record<string, any>)['completion_tokens'] === undefined)) return false;
    if ((!('totalTokens' in (value as Record<string, any>)) && !('total_tokens' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalTokens'] === undefined && (value as Record<string, any>)['total_tokens'] === undefined)) return false;
    return true;
}

export function UsageFromJSON(json: any): Usage {
    return UsageFromJSONTyped(json, false);
}

export function UsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usage {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function UsageToJSON(json: any): Usage {
    return UsageToJSONTyped(json, false);
}

export function UsageToJSONTyped(value?: Usage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
    };
}

