/* tslint:disable */
/* eslint-disable */
/**
 * deeprelay Public Developer API
 * Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@deeprelay.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One `/usage` row. Every row carries `bucket_start`, `gpu_seconds` and `cost_cents`. When the request set `modality` or `model` the row is an inference-usage row: it also carries `modality`, `model`, `prompt_tokens`, `completion_tokens` and `image_count` (aggregating every serverless inference call in the bucket for that modality and model), and `gpu_seconds` is always 0. Otherwise it is an instance-usage row, carrying `instance_id` / `gpu_type` when `group_by` asked for them.
 * 
 * @export
 * @interface UsageBucket
 */
export interface UsageBucket {
    /**
     * Start of the time bucket (truncated to `bucket`).
     * @type {Date}
     * @memberof UsageBucket
     */
    bucketStart: Date;
    /**
     * Instance-usage rows with `group_by=instance_id` only.
     * @type {string}
     * @memberof UsageBucket
     */
    instanceId?: string;
    /**
     * Instance-usage rows with `group_by=gpu_type` only.
     * @type {string}
     * @memberof UsageBucket
     */
    gpuType?: string;
    /**
     * GPU instance seconds billed in the bucket. Always 0 on inference-usage rows.
     * @type {number}
     * @memberof UsageBucket
     */
    gpuSeconds: number;
    /**
     * Total cost of the row, in US cents.
     * @type {number}
     * @memberof UsageBucket
     */
    costCents: number;
    /**
     * Inference-usage rows only: the modality of the calls in this row (chat, image, video or embedding).
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    modality?: string;
    /**
     * Inference-usage rows only: the model `id` the calls in this row were made against.
     * 
     * @type {string}
     * @memberof UsageBucket
     */
    model?: string;
    /**
     * Inference-usage rows only. Sum of input tokens; 0 for modalities not billed per token.
     * @type {number}
     * @memberof UsageBucket
     */
    promptTokens?: number;
    /**
     * Inference-usage rows only. Sum of output tokens; 0 for modalities not billed per token.
     * @type {number}
     * @memberof UsageBucket
     */
    completionTokens?: number;
    /**
     * Inference-usage rows only. Sum of generated images; 0 for non-image modalities.
     * @type {number}
     * @memberof UsageBucket
     */
    imageCount?: number;
}

/**
 * Check if a given object implements the UsageBucket interface.
 */
export function instanceOfUsageBucket(value: object): value is UsageBucket {
    if ((!('bucketStart' in (value as Record<string, any>)) && !('bucket_start' in (value as Record<string, any>))) || ((value as Record<string, any>)['bucketStart'] === undefined && (value as Record<string, any>)['bucket_start'] === undefined)) return false;
    if ((!('gpuSeconds' in (value as Record<string, any>)) && !('gpu_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['gpuSeconds'] === undefined && (value as Record<string, any>)['gpu_seconds'] === undefined)) return false;
    if ((!('costCents' in (value as Record<string, any>)) && !('cost_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['costCents'] === undefined && (value as Record<string, any>)['cost_cents'] === undefined)) return false;
    return true;
}

export function UsageBucketFromJSON(json: any): UsageBucket {
    return UsageBucketFromJSONTyped(json, false);
}

export function UsageBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'bucketStart': (new Date(json['bucket_start'])),
        'instanceId': json['instance_id'] == null ? undefined : json['instance_id'],
        'gpuType': json['gpu_type'] == null ? undefined : json['gpu_type'],
        'gpuSeconds': json['gpu_seconds'],
        'costCents': json['cost_cents'],
        'modality': json['modality'] == null ? undefined : json['modality'],
        'model': json['model'] == null ? undefined : json['model'],
        'promptTokens': json['prompt_tokens'] == null ? undefined : json['prompt_tokens'],
        'completionTokens': json['completion_tokens'] == null ? undefined : json['completion_tokens'],
        'imageCount': json['image_count'] == null ? undefined : json['image_count'],
    };
}

export function UsageBucketToJSON(json: any): UsageBucket {
    return UsageBucketToJSONTyped(json, false);
}

export function UsageBucketToJSONTyped(value?: UsageBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket_start': value['bucketStart'].toISOString(),
        'instance_id': value['instanceId'],
        'gpu_type': value['gpuType'],
        'gpu_seconds': value['gpuSeconds'],
        'cost_cents': value['costCents'],
        'modality': value['modality'],
        'model': value['model'],
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'image_count': value['imageCount'],
    };
}

